In [1]:
import os

In [9]:
import os
for dirname, _, filenames in os.walk(r"C:\Users\Dell\Downloads\archive (5)"):
    for filename in filenames:
        print(os.path.join(dirname, filename))

C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\annotations_all.json
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\annotations_test.json
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y701.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y702.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y703.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y704.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y705.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y706.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y707.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y708.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y709.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y710.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y711.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST\y712.jpg
C:\Users\Dell\Downloads\archive (5)\Br35H-Mask-RCNN\TEST

In [2]:
all_data_dir = os.listdir(r"C:\Users\Dell\Downloads\archive (5)")

In [3]:
print(all_data_dir)

['Br35H-Mask-RCNN', 'no', 'pred', 'yes']


In [4]:
import cv2
import matplotlib.pyplot as plt
import os
import tensorflow as tf
from tensorflow import keras
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import normalize
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from tensorflow.keras.utils import to_categorical
%matplotlib inline

In [7]:
image_directory=(r"C:\Users\Dell\Downloads\archive (5)")

no_tumor_images=os.listdir(r"C:\Users\Dell\Downloads\archive (5)\no")
yes_tumor_images=os.listdir(r"C:\Users\Dell\Downloads\archive (5)\yes")
# initialize dataset and label arrays
dataset=[]
label=[]
# set input size
INPUT_SIZE=64

In [15]:
for i , image_name in enumerate(no_tumor_images):
    #read the image if its extension is .jpg
    if(image_name.split('.')[1]=='jpg'):
        image=cv2.imread(r"C:\Users\Dell\Downloads\archive (5)\no/"+image_name)
        image=Image.fromarray(image,'RGB')
        image=image.resize((INPUT_SIZE,INPUT_SIZE))
        dataset.append(np.array(image))
        label.append(0)

        
for i , image_name in enumerate(yes_tumor_images):
    if(image_name.split('.')[1]=='jpg'):
        image=cv2.imread(r"C:\Users\Dell\Downloads\archive (5)\yes/"+image_name)
        image=Image.fromarray(image, 'RGB')
        image=image.resize((INPUT_SIZE,INPUT_SIZE))
        dataset.append(np.array(image))
        label.append(1)

dataset=np.array(dataset)
label=np.array(label)

In [16]:
print(dataset)

[[[[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  ...

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]]


 [[[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  ...

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 

In [17]:
print(label)

[0 0 0 ... 1 1 1]


In [18]:
print(len(label))

3000


In [19]:
dataset = np.array(dataset) 
label = np.array(label)

In [20]:
x_train, x_test, y_train, y_test = train_test_split(dataset, label, test_size = 0.2, random_state = 42)
              
print(x_train.shape) 
print(y_train.shape) 

(2400, 64, 64, 3)
(2400,)


In [21]:
print(x_test.shape)
print(y_test.shape)

(600, 64, 64, 3)
(600,)


In [22]:
x_train = normalize( x_train, axis =1)
x_test = normalize( x_test, axis =1)

In [23]:
y_train = to_categorical(y_train, num_classes=2)
y_test = to_categorical(y_test, num_classes=2)

In [32]:
model = Sequential()

model.add(Conv2D(32, (3,3), input_shape = (INPUT_SIZE, INPUT_SIZE, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(32, (3,3), kernel_initializer = 'he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64, (3,3),  kernel_initializer = 'he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Dense(2))
model.add(Activation('sigmoid'))
#model.add(Activation('softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 62, 62, 32)        896       
                                                                 
 activation_11 (Activation)  (None, 62, 62, 32)        0         
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 31, 31, 32)       0         
 2D)                                                             
                                                                 
 conv2d_7 (Conv2D)           (None, 29, 29, 32)        9248      
                                                                 
 activation_12 (Activation)  (None, 29, 29, 32)        0         
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 14, 14, 32)       0         
 2D)                                                  

In [33]:
tf.keras.utils.plot_model(model,
                          to_file="model.png",
                          show_shapes=True,
                          expand_nested=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [34]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [35]:
model.fit(x_train, y_train, 
batch_size = 16, 
verbose = 1, epochs = 10, 
validation_data = (x_test, y_test),
shuffle = 'False')

Epoch 1/10
150/150 [==============================] - 10s 59ms/step - loss: 0.5679 - accuracy: 0.7196 - val_loss: 0.4442 - val_accuracy: 0.8283
Epoch 2/10
150/150 [==============================] - 9s 59ms/step - loss: 0.4419 - accuracy: 0.8092 - val_loss: 0.3777 - val_accuracy: 0.8667
Epoch 3/10
150/150 [==============================] - 9s 59ms/step - loss: 0.3333 - accuracy: 0.8675 - val_loss: 0.2813 - val_accuracy: 0.8917
Epoch 4/10
150/150 [==============================] - 9s 60ms/step - loss: 0.2547 - accuracy: 0.9046 - val_loss: 0.2143 - val_accuracy: 0.9217
Epoch 5/10
150/150 [==============================] - 9s 60ms/step - loss: 0.1866 - accuracy: 0.9296 - val_loss: 0.1931 - val_accuracy: 0.9217
Epoch 6/10
150/150 [==============================] - 9s 58ms/step - loss: 0.1274 - accuracy: 0.9550 - val_loss: 0.1532 - val_accuracy: 0.9400
Epoch 7/10
150/150 [==============================] - 9s 60ms/step - loss: 0.0867 - accuracy: 0.9704 - val_loss: 0.1060 - val_accuracy: 0.960

In [36]:
model.save('Brain Tumor detection.h5')

In [37]:
import cv2
from keras.models import load_model 
from PIL import Image
import numpy as np

model = load_model('Brain Tumor detection.h5')

In [41]:
image = cv2.imread(r"C:\Users\Dell\Downloads\archive (5)\pred/pred13.jpg") 
img = Image.fromarray(image)
img = img.resize((64,64))
img = np.array(img)
print(img)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 1  1  1]
  [ 4  4  4]
  [ 4  4  4]
  ...
  [ 2  2  2]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[ 8  8  8]
  [22 22 22]
  [22 22 22]
  ...
  [11 11 11]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 8  8  8]
  [22 22 22]
  [22 22 22]
  ...
  [11 11 11]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 8  8  8]
  [22 22 22]
  [22 22 22]
  ...
  [10 10 10]
  [ 0  0  0]
  [ 0  0  0]]]


In [42]:
input_img = np.expand_dims(img, axis=0)

result = model.predict(input_img)
print(result)

1/1 [==============================] - 0s 359ms/step
[[0. 1.]]


In [45]:
image = cv2.imread(r"C:\Users\Dell\Downloads\archive (5)\pred/pred3.jpg") # no tumor detected 
img = Image.fromarray(image)
img = img.resize((64,64))
img = np.array(img)
print(img)

[[[3 3 3]
  [3 3 3]
  [3 3 3]
  ...
  [3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]
  ...
  [3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]
  ...
  [3 3 3]
  [3 3 3]
  [3 3 3]]

 ...

 [[3 3 3]
  [3 3 3]
  [3 3 3]
  ...
  [3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]
  ...
  [3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]
  ...
  [3 3 3]
  [3 3 3]
  [3 3 3]]]


In [46]:
input_img = np.expand_dims(img, axis=0)

result = model.predict(input_img)
print(result)

1/1 [==============================] - 0s 31ms/step
[[1. 0.]]
